# Generated by Django 3.1.3 on 2020-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgSrc',
            field=models.ImageField(upload_to=''),
        ),
    ]
