# Generated by Django 3.1.3 on 2020-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201103_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgSrc',
            field=models.CharField(max_length=255),
        ),
    ]
